package com.googlecode.gycreative.dataconn;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

public final class Header {
  private Header() { }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface headerinfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 Proto = 1;
    boolean hasProto();
    int getProto();
    
    // required int32 TYPE = 2;
    boolean hasTYPE();
    int getTYPE();
    
    // required int32 Content_length = 3;
    boolean hasContentLength();
    int getContentLength();
    
    // required int32 SEQC = 4;
    boolean hasSEQC();
    int getSEQC();
  }
  public static final class headerinfo extends
      com.google.protobuf.GeneratedMessage
      implements headerinfoOrBuilder {
    // Use headerinfo.newBuilder() to construct.
    private headerinfo(Builder builder) {
      super(builder);
    }
    private headerinfo(boolean noInit) {}
    
    private static final headerinfo defaultInstance;
    public static headerinfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public headerinfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Header.internal_static_headerinfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Header.internal_static_headerinfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 Proto = 1;
    public static final int PROTO_FIELD_NUMBER = 1;
    private int proto_;
    public boolean hasProto() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getProto() {
      return proto_;
    }
    
    // required int32 TYPE = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int tYPE_;
    public boolean hasTYPE() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTYPE() {
      return tYPE_;
    }
    
    // required int32 Content_length = 3;
    public static final int CONTENT_LENGTH_FIELD_NUMBER = 3;
    private int contentLength_;
    public boolean hasContentLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getContentLength() {
      return contentLength_;
    }
    
    // required int32 SEQC = 4;
    public static final int SEQC_FIELD_NUMBER = 4;
    private int sEQC_;
    public boolean hasSEQC() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getSEQC() {
      return sEQC_;
    }
    
    private void initFields() {
      proto_ = 0;
      tYPE_ = 0;
      contentLength_ = 0;
      sEQC_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasProto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTYPE()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContentLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSEQC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, proto_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, tYPE_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, contentLength_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, sEQC_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, proto_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, tYPE_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, contentLength_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sEQC_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Header.headerinfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Header.headerinfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Header.headerinfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Header.headerinfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Header.headerinfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Header.headerinfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Header.headerinfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Header.headerinfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Header.headerinfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Header.headerinfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Header.headerinfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Header.headerinfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Header.internal_static_headerinfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Header.internal_static_headerinfo_fieldAccessorTable;
      }
      
      // Construct using Header.headerinfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        proto_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        tYPE_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        contentLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        sEQC_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Header.headerinfo.getDescriptor();
      }
      
      public Header.headerinfo getDefaultInstanceForType() {
        return Header.headerinfo.getDefaultInstance();
      }
      
      public Header.headerinfo build() {
        Header.headerinfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Header.headerinfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Header.headerinfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Header.headerinfo buildPartial() {
        Header.headerinfo result = new Header.headerinfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.proto_ = proto_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tYPE_ = tYPE_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.contentLength_ = contentLength_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sEQC_ = sEQC_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Header.headerinfo) {
          return mergeFrom((Header.headerinfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Header.headerinfo other) {
        if (other == Header.headerinfo.getDefaultInstance()) return this;
        if (other.hasProto()) {
          setProto(other.getProto());
        }
        if (other.hasTYPE()) {
          setTYPE(other.getTYPE());
        }
        if (other.hasContentLength()) {
          setContentLength(other.getContentLength());
        }
        if (other.hasSEQC()) {
          setSEQC(other.getSEQC());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasProto()) {
          
          return false;
        }
        if (!hasTYPE()) {
          
          return false;
        }
        if (!hasContentLength()) {
          
          return false;
        }
        if (!hasSEQC()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              proto_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              tYPE_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              contentLength_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sEQC_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 Proto = 1;
      private int proto_ ;
      public boolean hasProto() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getProto() {
        return proto_;
      }
      public Builder setProto(int value) {
        bitField0_ |= 0x00000001;
        proto_ = value;
        onChanged();
        return this;
      }
      public Builder clearProto() {
        bitField0_ = (bitField0_ & ~0x00000001);
        proto_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 TYPE = 2;
      private int tYPE_ ;
      public boolean hasTYPE() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTYPE() {
        return tYPE_;
      }
      public Builder setTYPE(int value) {
        bitField0_ |= 0x00000002;
        tYPE_ = value;
        onChanged();
        return this;
      }
      public Builder clearTYPE() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tYPE_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 Content_length = 3;
      private int contentLength_ ;
      public boolean hasContentLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getContentLength() {
        return contentLength_;
      }
      public Builder setContentLength(int value) {
        bitField0_ |= 0x00000004;
        contentLength_ = value;
        onChanged();
        return this;
      }
      public Builder clearContentLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        contentLength_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 SEQC = 4;
      private int sEQC_ ;
      public boolean hasSEQC() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getSEQC() {
        return sEQC_;
      }
      public Builder setSEQC(int value) {
        bitField0_ |= 0x00000008;
        sEQC_ = value;
        onChanged();
        return this;
      }
      public Builder clearSEQC() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sEQC_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:headerinfo)
    }
    
    static {
      defaultInstance = new headerinfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:headerinfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_headerinfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_headerinfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014header.proto\"O\n\nheaderinfo\022\r\n\005Proto\030\001 " +
      "\002(\005\022\014\n\004TYPE\030\002 \002(\005\022\026\n\016Content_length\030\003 \002(" +
      "\005\022\014\n\004SEQC\030\004 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_headerinfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_headerinfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_headerinfo_descriptor,
              new java.lang.String[] { "Proto", "TYPE", "ContentLength", "SEQC", },
              Header.headerinfo.class,
              Header.headerinfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
